import Link from "next/link";
import PlatformIcon from "@/components/PlatformIcon";

const networks = [
  { label: "Facebook", href: "https://www.facebook.com/rhevolvermx", icon: "facebook" as const },
  { label: "Instagram", href: "https://www.instagram.com/rhevolvermx", icon: "instagram" as const },
  { label: "TikTok", href: "https://www.tiktok.com/@rhevolvercdmx", icon: "tiktok" as const },
  { label: "X", href: "https://x.com/rhevolvercdmx", icon: "x" as const },
  { label: "YouTube", href: "https://www.youtube.com/@RhevolverMx", icon: "youtube" as const },
  { label: "WhatsApp", href: "https://whatsapp.com/channel/0029Vb8o6fODzgTKUBkxkH2o", icon: "whatsapp" as const },
];

export default function SiteFooter() {
  return <footer className="border-t border-white/10 bg-[#07080d] text-white"><div className="mx-auto max-w-[1440px] px-4 py-12 sm:px-6 lg:px-8"><div className="grid gap-10 md:grid-cols-2 lg:grid-cols-[1.25fr_.75fr_.9fr_.9fr]">
    <div><Link href="/" className="inline-flex items-center gap-3"><div className="relative grid h-12 w-12 place-items-center overflow-hidden rounded-2xl bg-[#ffd400]"><span className="text-2xl font-black tracking-[-.12em] text-[#111827]">R<span className="text-fuchsia-600">.</span></span><div className="absolute inset-x-0 bottom-0 h-1 bg-gradient-to-r from-blue-600 to-fuchsia-600"/></div><div><p className="text-2xl font-black tracking-[-.05em]">Rhevolver<span className="text-fuchsia-500">.news</span></p><p className="text-[.62rem] font-bold uppercase tracking-[.2em] text-zinc-600">Información que revoluciona</p></div></Link><p className="mt-5 max-w-md text-sm leading-7 text-zinc-500">Casa editorial digital independiente con información local, estatal, nacional e internacional, análisis, tecnología y entretenimiento.</p><div className="mt-5 flex flex-wrap gap-2">{networks.map((n)=><a key={n.label} href={n.href} target="_blank" rel="noreferrer" aria-label={n.label} className="grid h-10 w-10 place-items-center rounded-full border border-white/10 bg-white/[.04] text-zinc-400 transition hover:-translate-y-.5 hover:border-fuchsia-400/50 hover:text-white"><PlatformIcon name={n.icon}/></a>)}</div></div>
    <div><h3 className="text-sm font-black uppercase tracking-[.18em] text-zinc-300">Secciones</h3><div className="mt-4 grid gap-3 text-sm text-zinc-500"><Link href="/categoria/local" className="hover:text-white">Local</Link><Link href="/categoria/guerrero" className="hover:text-white">Guerrero</Link><Link href="/categoria/nacional" className="hover:text-white">Nacional</Link><Link href="/categoria/politica" className="hover:text-white">Política</Link><Link href="/videos" className="hover:text-white">Videos</Link></div></div>
    <div><h3 className="text-sm font-black uppercase tracking-[.18em] text-zinc-300">Conócenos</h3><div className="mt-4 grid gap-3 text-sm text-zinc-500"><Link href="/sobre-rhevolver" className="hover:text-white">Sobre Rhevolver</Link><Link href="/mision-vision" className="hover:text-white">Misión, visión y valores</Link><Link href="/principios-editoriales" className="hover:text-white">Principios editoriales</Link><Link href="/transparencia" className="hover:text-white">Transparencia</Link><Link href="/contacto" className="hover:text-white">Contacto</Link></div></div>
    <div><h3 className="text-sm font-black uppercase tracking-[.18em] text-zinc-300">Legal</h3><div className="mt-4 grid gap-3 text-sm text-zinc-500"><Link href="/aviso-de-privacidad" className="hover:text-white">Aviso de privacidad</Link><Link href="/terminos-y-condiciones" className="hover:text-white">Términos y condiciones</Link><Link href="/politica-de-cookies" className="hover:text-white">Política de cookies</Link><Link href="/responsabilidad-editorial" className="hover:text-white">Responsabilidad editorial</Link><Link href="/publicidad-y-alianzas" className="hover:text-white">Publicidad y alianzas</Link><a href="mailto:rhevolvermedia@gmail.com" className="font-bold text-fuchsia-400 hover:text-fuchsia-300">rhevolvermedia@gmail.com</a></div></div>
  </div><div className="mt-10 flex flex-col gap-3 border-t border-white/10 pt-6 text-xs text-zinc-600 sm:flex-row sm:items-center sm:justify-between"><p>© {new Date().getFullYear()} Rhevolver Media Comunicaciones. Todos los derechos reservados.</p><p>Guerrero, México · Periodismo digital</p></div></div></footer>;
}
